(* Generated by Mirage (Thu, 19 Feb 2015 12:09:55 GMT). *)

open Lwt

let _ = Printexc.record_backtrace true

module Console = Console_unix

let console1 () =
  Console.connect "0"

module M2 = Unikernel.Client(Console)

let t2 = console1

let clock () = return (`Ok ())

let net_tap0 () =
  Netif.connect "tap0"

let random () = return (`Ok ())

module Stackv41 = struct
  module E = Ethif.Make(Netif)
  module I = Ipv4.Make(E)
  module U = Udp.Make(I)
  module T = Tcp.Flow.Make(I)(OS.Time)(Clock)(Random)
  module S = Tcpip_stack_direct.Make(Console)(OS.Time)(Random)(Netif)(E)(I)(U)(T)
  include S
end

let stackv41 () =
  console1 () >>= function
  | `Error _    -> fail (Failure "console1")
  | `Ok console ->
  net_tap0 () >>= function
  | `Error e      ->
    fail (Failure (Mirage_runtime.string_of_network_init_error "net_tap0" e))
  | `Ok interface ->
  let config = {
    V1_LWT.name = "stackv41";
    console; interface;
    mode = `IPv4 (Ipaddr.V4.of_string_exn "192.168.1.2", Ipaddr.V4.of_string_exn "255.255.255.0", [Ipaddr.V4.of_string_exn "192.168.1.1"]);
  } in
  Stackv41.connect config

module M1 = Unikernel.Client(Console)(Stackv41)

let t1 () =
  console1 () >>= function
  | `Error e -> fail (Failure "console1")
  | `Ok console1 ->
  stackv41 () >>= function
  | `Error e -> fail (Failure "stackv41")
  | `Ok stackv41 ->
  M1.start console1 stackv41

let () =
  OS.Main.run (join [t1 ()])
